config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :odds do
    member do
      get :friends
    end
  end
  resources :bets do
    member do
      get :updatebet
      get :placebet
      get :confirm
      get :allbets
      get :receive
      get :cancel
    end
  end
  resources :comments, only: [:create, :destroy]
  devise_for :users
  resources :users do
    member do
      get :friends
      get :followers
      get :deactivate
      get :mentionable
      get :funds
    end
  end

  resources :events do
    collection do
      get :calendar
    end
  end

  authenticated :user do
    root to: 'home#index', as: 'home'
  end
  unauthenticated :user do
    root 'home#front'
  end

  match :follow, to: 'follows#create', as: :follow, via: :post
  match :unfollow, to: 'follows#destroy', as: :unfollow, via: :post
  match :like, to: 'likes#create', as: :like, via: :post
  match :unlike, to: 'likes#destroy', as: :unlike, via: :post
  match :find_friends, to: 'home#find_friends', as: :find_friends, via: :get
  match :about, to: 'home#about', as: :about, via: :get
  match :allbets_home_page, to: 'home#allbets_home_page', as: :allbets_home_page, via: :get
  match :funds, to: 'users#funds', as: :funds, via: :post

end

app/models/comment.rb
# Copyright (c) 2015, @sudharti(Sudharsanan Muralidharan)
# Socify is an Open source Social network written in Ruby on Rails This file is licensed
# under GNU GPL v2 or later. See the LICENSE.

class Comment < ActiveRecord::Base
  include Shared::Callbacks
  include ActsAsCommentable::Comment
  include Mention

  belongs_to :commentable, polymorphic: true, counter_cache: true
  default_scope -> { order('created_at DESC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  # acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user

  include PublicActivity::Model
  tracked only: [:create], owner: proc { |_controller, model| model.user }

  validates_presence_of :comment
  validates_presence_of :commentable
  validates_presence_of :user

  auto_html_for :comment do
    image
    youtube(width: 400, height: 250, autoplay: true)
    link target: '_blank', rel: 'nofollow'
    simple_format
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_commentable, only: :create
  respond_to :js

  def create
    @comment = @commentable.comments.new do |comment|
      comment.comment = params[:comment_text]
      comment.user = current_user
    end
    @comment.save
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment_id = params[:id]
    @comment.destroy
  end

  private
  def find_commentable
    @commentable_type = params[:commentable_type].classify
    @commentable = @commentable_type.constantize.find(params[:commentable_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% if comment.user %>
  <div id="comment-<%= comment.id %>">
    <div class="info">
      <%= render 'shared/avatar', user: comment.user %>
      <h4 class="name"><%= link_to comment.user.name, user_path(comment.user) %></h4>
    </div>
    <div class="content">
      <div class="row">
        <span class="text"><%= comment.comment_html %></span>
      </div>
      <div class="pull-right">
        <% if belongs_to_user?(comment) %>
          <%= link_to comment_path(comment), method: :delete, class: 'btn btn-danger btn-sm', remote: true do %>
            <% fa_icon 'trash' %>
          <% end %>
        <% end %>
      </div>
    </div>
    <br>
    <hr>
  </div>
<% end %>

app/views/comments/_form.html.erb
<div id="mentionable-data" data-content="<%= mentionable_user_path(current_user) %>"></div>
<%= form_tag comments_path(commentable_type: commentable.class.to_s, commentable_id: commentable.id), id: 'new_comment', method: :post, remote: true do %>
  <div class="form-group">
    <div id="comment-text" contenteditable="true" class="editable form-control input-mentionable" placeholder="Enter Comment"></div>
    <%= hidden_field_tag :comment_text, nil, placeholder: 'Enter Comment', class: 'form-control input-mentionable' %>
  </div>
  <%= submit_tag :comment, class: 'btn btn-primary' %>
<% end %>

app/views/comments/create.js.erb
$("#<%= @commentable_type.downcase %>-<%= @commentable.id %> .comments").prepend("<%=j render(@comment) %>");
$("#comment_text").val("");

app/views/comments/destroy.js.erb
$("#comment-<%= @comment.id %>").remove();