config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :odds do
    member do
      get :friends
    end
  end
  resources :bets do
    member do
      get :updatebet
      get :placebet
      get :confirm
      get :allbets
      get :receive
      get :cancel
    end
  end
  resources :comments, only: [:create, :destroy]
  devise_for :users
  resources :users do
    member do
      get :friends
      get :followers
      get :deactivate
      get :mentionable
      get :funds
    end
  end

  resources :events do
    collection do
      get :calendar
    end
  end

  authenticated :user do
    root to: 'home#index', as: 'home'
  end
  unauthenticated :user do
    root 'home#front'
  end

  match :follow, to: 'follows#create', as: :follow, via: :post
  match :unfollow, to: 'follows#destroy', as: :unfollow, via: :post
  match :like, to: 'likes#create', as: :like, via: :post
  match :unlike, to: 'likes#destroy', as: :unlike, via: :post
  match :find_friends, to: 'home#find_friends', as: :find_friends, via: :get
  match :about, to: 'home#about', as: :about, via: :get
  match :allbets_home_page, to: 'home#allbets_home_page', as: :allbets_home_page, via: :get
  match :funds, to: 'users#funds', as: :funds, via: :post

end

app/models/concerns/shared/callbacks.rb
# Copyright (c) 2015, @sudharti(Sudharsanan Muralidharan)
# Socify is an Open source Social network written in Ruby on Rails This file is licensed
# under GNU GPL v2 or later. See the LICENSE.

module Shared::Callbacks
  extend ActiveSupport::Concern

  included do
    before_destroy :remove_activity
    before_destroy :remove_likes
  end

  def remove_activity
    activity = PublicActivity::Activity.find_by(trackable_id: self.id, trackable_type: self.class.to_s, key: "#{self.class.to_s.downcase}.create")
    activity.destroy if activity.present?
    true
  end

  def remove_likes
    activity = PublicActivity::Activity.find_by(trackable_id: self.id, trackable_type: self.class.to_s, key: "#{self.class.to_s.downcase}.like")
    activity.destroy if activity.present?
  end

end

app/views/shared/_actions.html.erb
<% if user_signed_in? %>
  <div class="actions">
    <div class="row">
      <div class="col-xs-6 like">
        <%= render 'likes/form', likeable: resource %>
      </div>
      <div class="col-xs-6 comment">
        <%= link_to resource, class: 'btn btn-block' do %>
          <%= fa_icon 'comment' %> comment
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_activity.html.erb
<%= render_activity(activity) %>

app/views/shared/_avatar.html.erb
<% if user %>
  <%= link_to user_path(user) do %>
    <%= image_tag user.avatar.url || 'avatar.jpg', class: 'avatar' %>
  <% end %>
<% end %>

app/views/shared/_cover.html.erb
<% if user.cover.url %>
  <div class="cover" style="background-image: url(<%= user.cover.url %>);"></div>
<% else %>
  <div class="cover" style="background-image: url(/assets/cover.png);"></div>
<% end %>

app/views/shared/_created_at.html.erb
<div class="created-at">
  <%= fa_icon 'clock-o' %>
  <%= relative_time(activity.created_at) %> ago
</div>

app/views/shared/_links.html.erb
<div id="links" class="well">
  <h5>
    <%= fa_icon 'newspaper-o' %>
    <%= link_to 'Betwork Board', root_path %>
  </h5>
  <h5>
    <%= fa_icon 'money' %>
    <%= link_to 'My Bets', allbets_bet_path(current_user) %>
  </h5>
  <h5>
    <%= fa_icon 'money' %>
    <%= link_to 'Live Bets', odds_path %>
  </h5>
  <h5>
    <%= fa_icon 'money' %>
    <%= link_to 'Manage Funds', funds_user_path(current_user) %>
  </h5>
  <h5>
    <%= fa_icon 'arrow-circle-right' %>
    <%= link_to 'Friends', friends_user_path(current_user) %>
  </h5>
  <h5>
    <%= fa_icon 'arrow-circle-left' %>
    <%= link_to 'Betwork Groups', groups_path %>
  </h5>
  <h5>
    <%= fa_icon 'search' %>
    <%= link_to('Find Friends', find_friends_path) %>
  </h5>
  <h5>
    <%= fa_icon 'pencil' %>
    <%= link_to 'Edit Profile', edit_user_path(current_user) %>
  </h5>
  <h5>
    <%= fa_icon 'lock' %>
    <%= link_to 'Change password', edit_user_registration_path %>
  </h5>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-top">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Betwork", root_url, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="navbar-top">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to('Profile', user_path(current_user)) %></li>
              <li><%= link_to 'Edit Profile', edit_user_path(current_user) %></li>
              <li><%= link_to 'Change password', edit_user_registration_path %></li>
              <li><%= link_to('Sign out', destroy_user_session_path, method: :delete) %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'About', about_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
          <li><%= link_to 'Sign in', user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_no_resource.html.erb
<div class="no-resource text-center">
  <h5>No <%= resources %> found.</h5>
</div>

app/views/shared/_paginate.html.erb
<div id="endless-scroll" class="well text-center hidden">
  <%= image_tag 'ajax-loader.gif' %>
  <%= will_paginate resources %>
</div>

app/views/shared/_paginate.js.erb
<% if resources.next_page %>
  $(".pagination").replaceWith("<%= j will_paginate(resources) %>");
  $(".pagination").hide();
<% else %>
  $(window).off('scroll');
  $("#endless-scroll").remove();
<% end %>

app/views/shared/_user_info.html.erb
<div id="user-info" class="well">
  <div class="text-center">
    <%= render 'shared/avatar', user: @user %><br>
    <h5><%= link_to @user.name, @user %></h5>
  </div>
  <h4>Actual Balance</h4>
  <h5><%= fa_icon 'money' %> <%= pluralize(@user.actualBalance, 'dollars') %></h5>
  <h4>Pending Bets</h4>
  <h5><%= fa_icon 'money' %> <%= pluralize(@user.balanceInEscrow, 'dollars') %></h5>
  <h4>Available Balance</h4>
  <h5><%= fa_icon 'money' %> <%= pluralize(@user.actualBalance - @user.balanceInEscrow, 'dollars') %></h5>
  <br>
  <div class="text-center">
    <% unless is_current_user?(@user) %>
      <%= render 'follows/form', user: @user %>
      <h6><%= 'Follows you' if current_user.followed_by?(@user) %></h6>
    <% end %>
  </div>
</div>