config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :odds do
    member do
      get :friends
    end
  end
  resources :bets do
    member do
      get :updatebet
      get :placebet
      get :confirm
      get :allbets
      get :receive
      get :cancel
    end
  end
  resources :comments, only: [:create, :destroy]
  devise_for :users
  resources :users do
    member do
      get :friends
      get :followers
      get :deactivate
      get :mentionable
      get :funds
    end
  end

  resources :events do
    collection do
      get :calendar
    end
  end

  authenticated :user do
    root to: 'home#index', as: 'home'
  end
  unauthenticated :user do
    root 'home#front'
  end

  match :follow, to: 'follows#create', as: :follow, via: :post
  match :unfollow, to: 'follows#destroy', as: :unfollow, via: :post
  match :like, to: 'likes#create', as: :like, via: :post
  match :unlike, to: 'likes#destroy', as: :unlike, via: :post
  match :find_friends, to: 'home#find_friends', as: :find_friends, via: :get
  match :about, to: 'home#about', as: :about, via: :get
  match :allbets_home_page, to: 'home#allbets_home_page', as: :allbets_home_page, via: :get
  match :funds, to: 'users#funds', as: :funds, via: :post

end

app/models/event.rb
class Event < ActiveRecord::Base
  include Shared::Callbacks
  belongs_to :user
  acts_as_votable
  acts_as_commentable

  include PublicActivity::Model
  tracked only: [:create, :like], owner: Proc.new{ |controller, model| model.user }

  validates_presence_of :name
  validates_presence_of :event_datetime
  validates_presence_of :user
end

app/controllers/events_controller.rb
# # Copyright (c) 2015, @sudharti(Sudharsanan Muralidharan)
# # Socify is an Open source Social network written in Ruby on Rails This file is licensed
# # under GNU GPL v2 or later. See the LICENSE.

# class EventsController < ApplicationController
#   before_action :set_user
#   before_action :authenticate_user!
#   before_action :set_event, only: [:edit, :update, :show, :destroy]

#   def new
#     @event = Event.new
#   end

#   def create
#     @event = current_user.events.new(event_params)
#     if @event.save
#       redirect_to root_path
#     else
#       render 'new', notice: @event.errors.full_messages.first
#     end
#   end

#   def edit
#     @event.event_datetime = @event.event_datetime.strftime("%Y/%m/%d %H:%M")
#   end

#   def show
#     @comments = @event.comments
#   end

#   def update
#     @event.update(event_params)
#     redirect_to @event
#   end

#   def destroy
#     @event.destroy
#     respond_to do |format|
#       format.js
#       format.html { redirect_to root_path }
#     end
#   end

#   def calendar
#     if request.xhr?
#       friend_events = Event.select("events.*").joins("INNER JOIN follows ON events.user_id = follows.followable_id").where("follows.follower_id = #{current_user.id} AND follows.followable_type ='User'")
#       current_user_events = current_user.events
#       @events = Event.from("(#{friend_events.to_sql} UNION #{current_user_events.to_sql}) as events").where("events.event_datetime BETWEEN '#{params[:start]}' AND '#{params[:end]}'")
#     end
#     respond_to do |format|
#       format.html
#       format.json { render :json => @events, each_serializer: EventCalendarSerializer }
#     end
#   end

#   private
#   def event_params
#     params.require(:event).permit(:name, :event_datetime)
#   end

#   def set_event
#     @event = Event.find_by(id: params[:id])
#     render_404 and return unless @event && User.find_by(id: @event.user_id)
#   end

#   def set_user
#     @user = current_user
#   end
# end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<% if event.user %>
  <div class="info">
    <%= render 'shared/avatar', user: event.user %>
    <h4 class="name"><%= link_to event.user.name, user_path(event.user) %></h4>
    <span class="action">created an <%= link_to 'event', event %></span>
  </div>
  <div class="content">
    <h3><%= event.name %></h3>
    <span class="text">
      <%= fa_icon'calendar' %> <%= formatted_time(event.event_datetime) %>
    </span>
    <%= render 'shared/created_at', activity: event %>
    <div class="points">
      <span class="like-count"><%= pluralize(event.cached_votes_up, 'like') %></span>
      <span class="comment-count"><%= pluralize(event.comments_count, 'comment') %></span>
      <div class="pull-right">
        <% if belongs_to_user?(event) %>
          <%= link_to edit_event_path(event), class: 'btn btn-primary btn-sm' do %>
            <% fa_icon 'pencil' %>
          <% end %>
          <%= link_to event_path(event), method: :delete, class:'btn btn-danger btn-sm', remote: remote do %>
            <% fa_icon 'trash' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <%= render 'shared/actions', resource: event %>
<% end %>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <div class="form-group">
    <%= f.label :event_name %>
    <%= f.text_field :name, autofocus: true, placeholder: 'Event Name', class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :when? %>
    <%= f.text_field :event_datetime, placeholder: 'When is it?', class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit (@event.persisted? ? :update : :create), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/events/calendar.html.erb
<div class="row">
  <div class="col-lg-3">
    <%= render 'shared/user_info' %>
  </div>
  <div class="col-lg-6 well">
    <h3>Events Calendar</h3>
    <hr>
    <div id="calendar"></div>
  </div>
  <div class="col-lg-3">
    <%= render 'shared/links' %>
  </div>
</div>

app/views/events/destroy.js.erb
$("#event-<%= @event.id %>").parent().remove();

app/views/events/edit.html.erb
<div class="row">
  <div class="col-lg-3">
    <%= render 'shared/user_info' %>
  </div>
  <div class="col-lg-6 well">
    <%= render 'form' %>
  </div>
  <div class="col-lg-3">
    <%= render 'shared/links' %>
  </div>
</div>

app/views/events/new.html.erb
<div class="row">
  <div class="col-lg-3">
    <%= render 'shared/user_info' %>
  </div>
  <div class="col-lg-6 well">
    <%= render 'form' %>
  </div>
  <div class="col-lg-3">
    <%= render 'shared/links' %>
  </div>
</div>

app/views/events/show.html.erb
<% if @event.user %>
  <div id="event-<%= @event.id %>" class="event">
    <div class="row">
      <div class="col-lg-6 col-lg-offset-3 well">
        <%= render @event, remote: false %>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-6 col-lg-offset-3 well">
        <h4>Comments</h4>
        <hr>
        <%= render 'comments/form', commentable: @event %>
        <br>
        <div class="comments">
          <%= render(@comments) || render('shared/no_resource', resources: 'Comments') %>
        </div>
      </div>
    </div>
  </div>
<% end %>