config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :odds do
    member do
      get :friends
    end
  end
  resources :bets do
    member do
      get :updatebet
      get :placebet
      get :confirm
      get :allbets
      get :receive
      get :cancel
    end
  end
  resources :comments, only: [:create, :destroy]
  devise_for :users
  resources :users do
    member do
      get :friends
      get :followers
      get :deactivate
      get :mentionable
      get :funds
    end
  end

  resources :events do
    collection do
      get :calendar
    end
  end

  authenticated :user do
    root to: 'home#index', as: 'home'
  end
  unauthenticated :user do
    root 'home#front'
  end

  match :follow, to: 'follows#create', as: :follow, via: :post
  match :unfollow, to: 'follows#destroy', as: :unfollow, via: :post
  match :like, to: 'likes#create', as: :like, via: :post
  match :unlike, to: 'likes#destroy', as: :unlike, via: :post
  match :find_friends, to: 'home#find_friends', as: :find_friends, via: :get
  match :about, to: 'home#about', as: :about, via: :get
  match :allbets_home_page, to: 'home#allbets_home_page', as: :allbets_home_page, via: :get
  match :funds, to: 'users#funds', as: :funds, via: :post

end

app/models/odd.rb
class Odd< ActiveRecord::Base
    include Shared::Callbacks
  
    acts_as_commentable
  
  
end
  

app/controllers/odds_controller.rb
require 'uri'
require 'net/http'
require 'openssl'
require 'json'
require 'date'

class OddsController < ApplicationController
  before_action :set_user

  def index

    team_names = {
      'ATL' => 'Atlanta Hawks',
      'BKN' => 'Brooklyn Nets',
      'BOS' => 'Boston Celtics',
      'CHA' => 'Charlotte Hornets',
      'CHI' => 'Chicago Bulls',
      'CLE' => 'Cleveland Cavaliers',
      'DAL' => 'Dallas Mavericks',
      'DEN' => 'Denver Nuggets',
      'DET' => 'Detroit Pistons',
      'GSW' => 'Golden State Warriors',
      'HOU' => 'Houston Rockets',
      'IND' => 'Indiana Pacers',
      'LAC' => 'Los Angeles Clippers',
      'LAL' => 'Los Angeles Lakers',
      'MEM' => 'Memphis Grizzlies',
      'MIA' => 'Miami Heat',
      'MIL' => 'Milwaukee Bucks',
      'MIN' => 'Minnesota Timberwolves',
      'NOP' => 'New Orleans Pelicans',
      'NYK' => 'New York Knicks',
      'OKC' => 'Oklahoma City Thunder',
      'ORL' => 'Orlando Magic',
      'PHI' => 'Philadelphia 76ers',
      'PHX' => 'Phoenix Suns',
      'POR' => 'Portland Trail Blazers',
      'SAC' => 'Sacramento Kings',
      'SAS' => 'San Antonio Spurs',
      'TOR' => 'Toronto Raptors',
      'UTA' => 'Utah Jazz',
      'WAS' => 'Washington Wizards'
    }

    team_names_NFL = {
      'ARZ' => 'Arizona Cardinals',
      'ATL' => 'Atlanta Falcons',
      'BLT' => 'Baltimore Ravens',
      'BUF' => 'Buffalo Bills',
      'CAR' => 'Carolina Panthers',
      'CHI' => 'Chicago Bears',
      'CIN' => 'Cincinnati Bengals',
      'CLV' => 'Cleveland Browns',
      'DAL' => 'Dallas Cowboys',
      'DEN' => 'Denver Broncos',
      'DET' => 'Detroit Lions',
      'GB' => 'Green Bay Packers',
      'HST' => 'Houston Texans',
      'IND' => 'Indianapolis Colts',
      'JAX' => 'Jacksonville Jaguars',
      'KC' => 'Kansas City Chiefs',
      'LV' => 'Las Vegas Raiders',
      'LAC' => 'Los Angeles Chargers',
      'LA' => 'Los Angeles Rams',
      'MIA' => 'Miami Dolphins',
      'MIN' => 'Minnesota Vikings',
      'NE' => 'New England Patriots',
      'NO' => 'New Orleans Saints',
      'NYG' => 'New York Giants',
      'NYJ' => 'New York Jets',
      'PHI' => 'Philadelphia Eagles',
      'PIT' => 'Pittsburgh Steelers',
      'SF' => 'San Francisco 49ers',
      'SEA' => 'Seattle Seahawks',
      'TB' => 'Tampa Bay Buccaneers',
      'TEN' => 'Tennessee Titans',
      'WAS' => 'Washington Commanders'
    }

    # puts "execute index"
    # puts params
    @odds = Odd.all
    Odd.delete_all

    # CREATING AN OLD NBA GAME

    # send the API request for NBA games
    url = URI("https://odds.p.rapidapi.com/v4/sports/basketball_nba/scores?daysFrom=3")
    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    request = Net::HTTP::Get.new(url)
    request["X-RapidAPI-Key"] = 'b75f06b51amshedbb7bbb363591fp1d8c49jsnea0e9ea45d3b'
    request["X-RapidAPI-Host"] = 'odds.p.rapidapi.com'
    response = http.request(request)
    nba_games = JSON.parse(response.read_body)

    # team names
    home_team_name = nba_games[0]['home_team']
    away_team_name = nba_games[0]['away_team']

    # getting the start time of the game in UTC
    date_string = nba_games[0]['commence_time']
    date_object_utc = DateTime.strptime(date_string, '%Y-%m-%dT%H:%M:%s')

    # offsetting the time to EST
    eastern_offset = Rational(-5, 24)
    date_object_eastern = date_object_utc.new_offset(eastern_offset)
    date_string_eastern = date_object_eastern.strftime('%H:%M ET %m/%d/%Y')

    # create the odd based on the oldest game from scores
    old_odd = Odd.create!(
      "home_team_name": home_team_name,
      "away_team_name": away_team_name,
      "home_money_line": -210,
      "away_money_line": 175,
      "date": date_string_eastern,
      "toolate": false,
      "league": "NBA"
    )
    old_odd.save




    # CREATING AN OLD NHL GAME

    # send the API request for NHL games
    url = URI("https://odds.p.rapidapi.com/v4/sports/icehockey_nhl/scores?daysFrom=3")
    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    request = Net::HTTP::Get.new(url)
    request["X-RapidAPI-Key"] = 'b75f06b51amshedbb7bbb363591fp1d8c49jsnea0e9ea45d3b'
    request["X-RapidAPI-Host"] = 'odds.p.rapidapi.com'
    response = http.request(request)
    nhl_games = JSON.parse(response.read_body)

    # team names
    home_team_name = nhl_games[0]['home_team']
    away_team_name = nhl_games[0]['away_team']

    # getting the start time of the game in UTC
    date_string = nhl_games[0]['commence_time']
    date_object_utc = DateTime.strptime(date_string, '%Y-%m-%dT%H:%M:%s')

    # offsetting the time to EST
    eastern_offset = Rational(-5, 24)
    date_object_eastern = date_object_utc.new_offset(eastern_offset)
    date_string_eastern = date_object_eastern.strftime('%H:%M ET %m/%d/%Y')

    # create the odd based on the oldest game from scores
    old_odd = Odd.create!(
      "home_team_name": home_team_name,
      "away_team_name": away_team_name,
      "home_money_line": -210,
      "away_money_line": 175,
      "date": date_string_eastern,
      "toolate": false,
      "league": "NHL"
    )
    old_odd.save




    odds = find_nba_odds()
    if odds != nil
      odds.each do |odd|

        # checking if the odd is non-Null
        if (!odd['home_team'].nil? and
          !odd['away_team'].nil?)

          # extracting the home and away team names
          home_team_name = odd['home_team']
          away_team_name = odd['away_team']

          # getting the start time of the game in UTC
          date_string = odd['commence_time']
          date_object_utc = DateTime.strptime(date_string, '%Y-%m-%dT%H:%M:%s')

          # offsetting the time to EST
          eastern_offset = Rational(-5, 24)
          date_object_eastern = date_object_utc.new_offset(eastern_offset)
          date_string_eastern = date_object_eastern.strftime('%H:%M ET %m/%d/%Y')

          # comparing current time in EST to 2hrs before start time of game in eastern
          early_time_eastern = date_object_eastern - (2/24.0)
          current_time = DateTime.now
          current_time_eastern = current_time.new_offset(eastern_offset)
          toolate_boolean = current_time_eastern > early_time_eastern

          # extracting the home and away team odds
          if (odd['bookmakers'][0]['markets'][0]['outcomes'][0]['name'] == home_team_name)
            home_team_odds = odd['bookmakers'][0]['markets'][0]['outcomes'][0]['price']
            away_team_odds = odd['bookmakers'][0]['markets'][0]['outcomes'][1]['price']
          else
            home_team_odds = odd['bookmakers'][0]['markets'][0]['outcomes'][1]['price']
            away_team_odds = odd['bookmakers'][0]['markets'][0]['outcomes'][0]['price']
          end

          new_odd = Odd.create!(
            "home_team_name": home_team_name,
            "away_team_name": away_team_name,
            "home_money_line": home_team_odds,
            "away_money_line": away_team_odds,
            "date": date_string_eastern,
            "toolate": toolate_boolean,
            "league": "NBA"
          )
          new_odd.save
        end
      end
    end

    odds = find_nfl_odds()
    if odds != nil
      odds.each do |odd|

        # checking if the odd is non-Null
        if (!odd['home_team'].nil? and
          !odd['away_team'].nil?)

          # extracting the home and away team names
          home_team_name = odd['home_team']
          away_team_name = odd['away_team']

          # getting the start time of the game in UTC
          date_string = odd['commence_time']
          date_object_utc = DateTime.strptime(date_string, '%Y-%m-%dT%H:%M:%s')

          # offsetting the time to EST
          eastern_offset = Rational(-5, 24)
          date_object_eastern = date_object_utc.new_offset(eastern_offset)
          date_string_eastern = date_object_eastern.strftime('%H:%M ET %m/%d/%Y')

          # comparing current time in EST to 2hrs before start time of game in eastern
          early_time_eastern = date_object_eastern - (2/24.0)
          current_time = DateTime.now
          current_time_eastern = current_time.new_offset(eastern_offset)
          toolate_boolean = current_time_eastern > early_time_eastern

          # extracting the home and away team odds
          if (odd['bookmakers'][0]['markets'][0]['outcomes'][0]['name'] == home_team_name)
            home_team_odds = odd['bookmakers'][0]['markets'][0]['outcomes'][0]['price']
            away_team_odds = odd['bookmakers'][0]['markets'][0]['outcomes'][1]['price']
          else
            home_team_odds = odd['bookmakers'][0]['markets'][0]['outcomes'][1]['price']
            away_team_odds = odd['bookmakers'][0]['markets'][0]['outcomes'][0]['price']
          end

          new_odd = Odd.create!(
            "home_team_name": home_team_name,
            "away_team_name": away_team_name,
            "home_money_line": home_team_odds,
            "away_money_line": away_team_odds,
            "date": date_string_eastern,
            "toolate": toolate_boolean,
            "league": "NFL"
          )
          new_odd.save
        end
      end
    end

    odds = find_nhl_odds()
    if odds != nil
      odds.each do |odd|

        # checking if the odd is non-Null
        if (!odd['home_team'].nil? and
          !odd['away_team'].nil?)

          # extracting the home and away team names
          home_team_name = odd['home_team']
          away_team_name = odd['away_team']

          # getting the start time of the game in UTC
          date_string = odd['commence_time']
          date_object_utc = DateTime.strptime(date_string, '%Y-%m-%dT%H:%M:%s')

          # offsetting the time to EST
          eastern_offset = Rational(-5, 24)
          date_object_eastern = date_object_utc.new_offset(eastern_offset)
          date_string_eastern = date_object_eastern.strftime('%H:%M ET %m/%d/%Y')

app/views/odds/_form.html.erb
<div class="follow">
<%= link_to 'Propose Bet', placebet_bet_path(amount: @amount,friend_id:user.id, game:@game), :class => 'btn btn-primary'%>
</div>

app/views/odds/friends.html.erb
<div class="row">
  <div class="col-lg-3">
  <table class="table table-striped col-md-12" id="bets">
  <thead>
    <tr>
	    <th>Home Team</th>
	    <th>Away Team</th>
      <th>Home Money Line</th>
      <th>Away Money Line</th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td>
          <%= @game.home_team_name%>
        </td>
        <td>
          <%= @game.away_team_name%>
        </td>
        <td>
          <%= @game.home_money_line%>
        </td>
        <td>
          <%= @game.away_money_line%>
        </td>

<!--        <td>-->
        <%#= link_to 'Place Bet', friends_odd_path(odd), :class => 'btn btn-primary' %>
<!--        </td>-->
      </tr>
    <%# end %>
  </tbody>
</table>
  </div>
  <div class="col-lg-6 well">
    <h3>Choose friend to place bet against</h3>
    <hr>
    <div id="friends">
      <%= render(@friends) || render('shared/no_resource', resources: 'Friends') %>
    </div>
    <%= render 'shared/paginate', resources: @friends %>
  </div>
  <div class="col-lg-3">
    <%= render 'shared/links' %>
  </div>
</div>

app/views/odds/friends.js.erb
$('#friends').append("<%= j render(@friends) %>");

<%= render 'shared/paginate', resources: @friends %>

app/views/odds/index.html.erb
<h2>NBA Odds</h2>

<table class="table table-striped col-md-12" id="bets">
  <thead>
    <tr>
	    <th>Home Team</th>
	    <th>Away Team</th>
      <th>Time & Date</th>
      <th>Home Money Line</th>
      <th>Away Money Line</th>
      <th>Place Bets</th>
    </tr>
  </thead>
  <tbody>
    <% @odds.each do |odd| %>
      <% if odd.league == 'NBA' %>
      <tr>
        <td>
          <%= odd.home_team_name%>
        </td>
        <td>
          <%= odd.away_team_name%>
        <td>
          <%= odd.date %>
        </td>
        <td>
          <%= odd.home_money_line%>
        </td>
        <td>
          <%= odd.away_money_line%>
        </td>
        <td>
        <% if !odd.home_money_line  || !odd.away_money_line || odd.toolate %>
        <%= link_to 'Propose Bet', friends_odd_path(odd, id:current_user.id), :class => 'btn btn-primary disabled' %>
        <%else%>
        <%= link_to 'Propose Bet', friends_odd_path(odd), :class => 'btn btn-primary' %>
        <%end%>
        </td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<h2>NFL Odds</h2>

<table class="table table-striped col-md-12" id="bets">
  <thead>
  <tr>
    <th>Home Team</th>
    <th>Away Team</th>
    <th>Time & Date</th>
    <th>Home Money Line</th>
    <th>Away Money Line</th>
    <th>Place Bets</th>
  </tr>
  </thead>
  <tbody>
  <% @odds.each do |odd| %>
    <% if odd.league == 'NFL' %>
      <tr>
        <td>
          <%= odd.home_team_name%>
        </td>
        <td>
          <%= odd.away_team_name%>
        <td>
          <%= odd.date %>
        </td>
        <td>
          <%= odd.home_money_line%>
        </td>
        <td>
          <%= odd.away_money_line%>
        </td>
        <td>
          <% if !odd.home_money_line  || !odd.away_money_line || odd.toolate %>
            <%= link_to 'Propose Bet', friends_odd_path(odd, id:current_user.id), :class => 'btn btn-primary disabled' %>
          <%else%>
            <%= link_to 'Propose Bet', friends_odd_path(odd), :class => 'btn btn-primary' %>
          <%end%>
        </td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>


<h2>NHL Odds</h2>

<table class="table table-striped col-md-12" id="bets">
  <thead>
  <tr>
    <th>Home Team</th>
    <th>Away Team</th>
    <th>Time & Date</th>
    <th>Home Money Line</th>
    <th>Away Money Line</th>
    <th>Place Bets</th>
  </tr>
  </thead>
  <tbody>
  <% @odds.each do |odd| %>
    <% if odd.league == 'NHL' %>
      <tr>
        <td>
          <%= odd.home_team_name%>
        </td>
        <td>
          <%= odd.away_team_name%>
        <td>
          <%= odd.date %>
        </td>
        <td>
          <%= odd.home_money_line%>
        </td>
        <td>
          <%= odd.away_money_line%>
        </td>
        <td>
          <% if !odd.home_money_line  || !odd.away_money_line || odd.toolate %>
            <%= link_to 'Propose Bet', friends_odd_path(odd, id:current_user.id), :class => 'btn btn-primary disabled' %>
          <%else%>
            <%= link_to 'Propose Bet', friends_odd_path(odd), :class => 'btn btn-primary' %>
          <%end%>
        </td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>